### ISSUE TITLE
Active Record 5.1 support

### ISSUE THREAD

**Issue by tbalthazar** [ConsultingMD/activerecord5-redshift-adapter#14]
Hi,

Thanks for making this adapter available.
I've been playing with it for a Rails 5.1 project, and had to patch a few methods to have it working (mainly method arity changes).
Would you accept PRs for Active Record 5.1 on this repo, or is it meant to only support AR 5.0?

Thanks!
Thomas.

**Comment by yllihv27** [comment]
Hi @tbalthazar do you have a working redshift adapter for rails 5.1?

**Comment by tbalthazar** [comment]
@yllihv27 I don't.
