### ISSUE TITLE
(uninitialized constant ActiveRecord::ConnectionAdapters::RedshiftAdapter::PGconn

### ISSUE THREAD

**Issue by techbrownbags** [ConsultingMD/activerecord5-redshift-adapter#16]
I must be missing something simple. When i try to get gat via a model I'm getting 
NameError (uninitialized constant ActiveRecord::ConnectionAdapters::RedshiftAdapter::PGconn):

rails 5.1.6
pg (1.0.0)
activerecord5-redshift-adapter (1.0)

**Comment by techbrownbags** [comment]
I also tried rails 5.0.0 and 5.0.6

**Comment by jesusangelm** [comment]
same here

**Comment by techbrownbags** [comment]
closing, getting from master instead of v1 and it works
