### ISSUE TITLE
Version pegged to activerecord ~5.0.0 --> is there a reason it is incompatible with 5.1?

### ISSUE THREAD

**Issue by tmartyny** [ConsultingMD/activerecord5-redshift-adapter#5]
And do you know what we'd need to change to make it work for 5.1? Would be happy to make a PR if you gave us suggestions.

-Teresa & https://github.com/FeminismIsAwesome

**Comment by taurauko** [comment]
It's already fixed: https://github.com/ConsultingMD/activerecord5-redshift-adapter/commit/9578912853793a1106777ea163f7b296e55f1508

It's just not reflected on rubygems.

**Comment by KOBA789** [comment]
It seems that @nfoen and @RoryO have the permission to push the gem.
@nfoen or @RoryO, could you push it to rubygems.org?

**Comment by RoryO** [comment]
Released to rubygems. Sorry about that.
