### ISSUE TITLE
Cannot find the right name to load the gem

### ISSUE THREAD

**Issue by designium** [ConsultingMD/activerecord5-redshift-adapter#8]
Hi,

I'm trying to use the gem as a standalone script with Active Record. I need to require the gem but I cannot find the name for it:

    irb(main):002:0> require 'activerecord-redshift-adapter'
     LoadError: cannot load such file -- activerecord-redshift-adapter
    	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    	from (irb):2
    	from /usr/local/var/rbenv/versions/2.4.0/bin/irb:11:in `<main>'
     irb(main):003:0>

#What is the name for require?

**Comment by cobbr2** [comment]
activerecord5-redshift-adapter

-- ReC

Rick Cobb / Architect

Grand Rounds

Office: 1-800-929-0926  / Fax: 1-888-323-5997

360 3rd St, Suite 425,  San Francisco, CA 94107

http://www.grandroundshealth.com ​

[image: Facebook] <https://www.facebook.com/GrandRoundsHealth> [image:
Twitter] <https://twitter.com/GrandRoundsInc> [image: Linkedin]
<https://www.linkedin.com/company/grandrounds>

**Comment by designium** [comment]
I tried both and I made sure to have it installed.

    irb(main):002:0> require 'activerecord5-redshift-adapter'
     LoadError: cannot load such file -- activerecord5-redshift-adapter
    	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
    	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
    	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
    	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
    	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
	from (irb):2
	from /usr/local/var/rbenv/versions/2.4.0/bin/irb:11:in `<main>'
     irb(main):003:0>

Here is my gem list:

$ gem list

*** LOCAL GEMS ***

actioncable (5.1.1)
actionmailer (5.1.1)
actionpack (5.1.1)
actionview (5.1.1)
activejob (5.1.1)
activemodel (5.1.1, 5.1.0)
activerecord (5.1.1, 5.1.0)
activerecord5-redshift-adapter (1.0)
activesupport (5.1.1, 5.1.0)
addressable (2.5.1)
arel (8.0.0)
awesome_print (1.7.0)
bigdecimal (default: 1.3.0)
bindex (0.5.0)
bond (0.5.1)
builder (3.2.3)
bundler (1.15.1, 1.14.6)
byebug (9.0.6)
capybara (2.14.2, 2.14.1)
childprocess (0.7.0)
coderay (1.1.1)
coffee-rails (4.2.2)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
colorize (0.8.1)
concurrent-ruby (1.0.5)
czmq-ffi-gen (0.13.0)
cztop (0.11.4)
data_uri (0.1.0)
did_you_mean (1.1.0)
domain_name (0.5.20170404)
erubi (1.6.0)
execjs (2.7.0)
ffi (1.9.18)
ffi-rzmq (2.0.5)
ffi-rzmq-core (1.0.6)
geocoder (1.4.4)
globalid (0.4.0)
gnuplot (2.6.2)
haml (5.0.1)
http-cookie (1.0.3)
i18n (0.8.4, 0.8.1)
io-console (default: 0.4.6)
iruby (0.3)
jbuilder (2.7.0)
json (default: 2.0.2, 1.8.6)
lemmatizer (0.1.1)
listen (3.1.5)
loofah (2.0.3)
mail (2.6.6, 2.6.5)
mechanize (2.7.5)
method_source (0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mimemagic (0.3.2)
mini_portile2 (2.2.0, 2.1.0)
minitest (5.10.2, 5.10.1)
multi_json (1.12.1)
mustermann (1.0.0)
net-http-digest_auth (1.4.1)
net-http-persistent (2.9.4)
net-telnet (0.1.1)
nio4r (2.1.0)
nokogiri (1.8.0, 1.7.2)
ntlm-http (0.1.1)
nyaplot (0.1.6)
openssl (default: 2.0.2)
parallel (1.11.2)
pg (0.21.0)
power_assert (0.4.1)
progressbar (1.8.2)
pry (0.10.4)
pry-doc (0.10.0)
psych (default: 2.2.2)
public_suffix (2.0.5)
puma (3.9.1, 3.8.2)
rack (2.0.3, 2.0.2)
rack-protection (2.0.0)
rack-test (0.6.3)
rails (5.1.1)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.3)
railties (5.1.1)
rake (12.0.0)
rb-fsevent (0.9.8)
rb-inotify (0.9.8)
rdoc (default: 5.0.0)
ruby-progressbar (1.8.1)
ruby_dep (1.5.0)
rubyvis (0.6.1)
rubyzip (1.2.1)
sass (3.4.24)
sass-rails (5.0.6)
selenium-webdriver (3.4.1, 3.4.0)
sinatra (2.0.0)
sinatra-activerecord (2.0.13)
slop (3.6.0)
spring (2.0.2)
spring-watcher-listen (2.0.1)
sprockets (3.7.1)
sprockets-rails (3.2.0)
sqlite3 (1.3.13)
temple (0.8.0)
test-unit (3.2.3)
tf-idf-similarity (0.1.6)
tf_idf (0.0.2)
thor (0.19.4)
thread_safe (0.3.6)
tilt (2.0.7)
turbolinks (5.0.1)
turbolinks-source (5.0.3)
tzinfo (1.2.3)
uglifier (3.2.0)
unf (0.1.4)
unf_ext (0.0.7.4)
unicode_utils (1.4.0)
web-console (3.5.1)
webrobots (0.1.2)
websocket (1.2.4)
websocket-driver (0.6.5)
websocket-extensions (0.1.2)
xmlrpc (0.2.1)
xpath (2.1.0)
yard (0.9.9)

**Comment by designium** [comment]
Hi, 

I know how the gem works, we cannot call it directly from the gem but through Active Record gem and it becomes one of its adapter.

In order to use this plug in, we just need the following:

    class CLASS_NAME < ActiveRecord::Base
      ActiveRecord::Base.establish_connection(
          adapter: 'redshift',
          database: 'DB_NAME',
         encoding: 'utf8',
          port: 5439,
          pool: 5,
          schema_search_path: 'DB_SCHEMA_NAME',
          username: 'DB_USER_NAME',
          password: 'DB_USER_PASSWORD',
          host: 'DB_HOST_AT_REDSHIFT',
          timeout: '5000'
          )
  
       self.table_name = "CUSTOM_TABLE_NAME"
     end
